### ISSUE TITLE
Screenshot??

### ISSUE THREAD

**Issue by PySimpleGUI** [uga-libraries/ASpace_Batch_Export-Cleanup-Upload#1]
Hi!

Was looking at your code and your GUI code looks like you've got a heck of a GUI.  I see a lot of stuff there.  I bet it looks great, but I can't tell.

I've found that repos that have a screenshot in their readme.md file get a LOT more visitors / people that will try the code than those without. 

Adding one is simple if you paste an image into one of these GitHub issues and then paste the code GitHub generates into the readme.md file.  This way you don't have to upload an image to your repo.

I would really like to see what you've made.

**Comment by crugas** [comment]
Pleasure to see a visitor!

I am more than happy to share an image or two, especially if it helps for discoverability. Currently, this repo is just a holding place for what I hope will be the final product. It's a bit haphazard, I know.

Still working on a few bugs, but I'll share a screenshot here an paste it to the readme.md. 

![homepage-ead-001](https://user-images.githubusercontent.com/62658840/81198762-d97a7d00-8f8f-11ea-9326-ad7da0ad6233.gif)

**Comment by PySimpleGUI** [comment]
Oh wow!  An animated GIF even!  Very nice!

I knew there was quite a bit of GUI for you to be able to show off!

**Comment by crugas** [comment]
I'm glad you like it! Thanks!

When it's ready to go into production, I'll make sure to add animated gifs for the different parts of the GUI, including the EAD section seen above, different radio options (MARCXML, Container Labels, PDF), Upload to XTF, and menu options.
